image: python

stages:
  - test
  - build
  - deploy

build_package:
  stage: build
  before_script:
    - python3 -m pip install --user --upgrade setuptools wheel
  script:
    - python3 setup.py sdist bdist_wheel

upload_package:
  stage: deploy
  only:
    - master
  before_script:
    - python3 -m pip install --user --upgrade twine
  script:
    - python3 -m twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
  artifacts:
    paths:
      - dist/

upload_package_test:
  stage: deploy
  except:
    - master
  before_script:
    - python3 -m pip install --user --upgrade twine
  script:
    - python3 -m twine upload --repository-url https://test.pypi.org/legacy/ -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*