image: python

stages:
  - test
  - build
  - deploy

unittest:
  stage: test
  before_script:
    - wget https://downloads.arduino.cc/arduino-cli/arduino-cli-latest-linux64.tar.bz2
    - ARDUINO_CLI=$(tar -xvjf arduino-cli-latest-linux64.tar.bz2)
    - rm arduino-cli-latest-linux64.tar.bz2
    - mv $ARDUINO_CLI arduino-cli
  script:
    - python -m unittest discover -s tests

build_package:
  stage: build
  before_script:
    - python3 -m pip install --user --upgrade setuptools wheel
  script:
    - python3 setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/

upload_package:
  stage: deploy
  only:
    - master
  before_script:
    - python3 -m pip install --user --upgrade twine
  script:
    - python3 -m twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
  dependencies:
    - build_package

upload_package_test:
  stage: deploy
  only:
    - prerelease
  before_script:
    - python3 -m pip install --user --upgrade twine
  script:
    - python3 -m twine upload --repository-url https://test.pypi.org/legacy/ -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
  dependencies:
    - build_package