name: Build
on:
  release:
    types:
      - released
      - prereleased
  push:
jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install build dependencies
        run: |
          python -m pip install wheel --user
      - name: Build binary wheel and source tarball
        run: |
          python setup.py sdist bdist_wheel
      - name: Upload build results
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  build-docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/_build/html/
  unit-test:
    name: Unit Tests
    needs: build
    strategy:
      matrix:
        python: ["3.9"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Download arduino-cli
        run: |
          wget https://github.com/arduino/arduino-cli/releases/download/v0.35.3/arduino-cli_0.35.3_Linux_64bit.tar.gz
          tar xzf arduino-cli_0.35.3_Linux_64bit.tar.gz
          rm arduino-cli_0.35.3_Linux_64bit.tar.gz
      - name: Install test dependencies
        run: |
          pip install pytest
      - name: Run tests
        run: |
          pytest
  deploy-docs:
    name: Deploy docs to GitHub pages
    if: github.ref == 'refs/heads/master'
    needs:
      - unit-test
      - build-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download built documentation
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs/_build/html/
      - name: Disables jekyll
        run: |
          touch docs/_build/html/.nojekyll
      - name: Publish on GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4
        with:
          branch: gh-pages
          folder: docs/_build/html
          clean: true
  deploy-on-test-pypi:
    name: Deploy on Test PyPI
    if: github.event_name == 'release'
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Download build results
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish to index
        uses: pypa/gh-action-pypi-publish@release/v1
        continue-on-error: true
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
  deploy-on-pypi:
    name: Deploy on PyPI
    if: github.event_name == 'release'
    needs: deploy-on-test-pypi
    runs-on: ubuntu-latest
    steps:
      - name: Download build results
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish to index
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
